version: 2.0
jobs:

  unittests:
    working_directory: ~/repo
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:  pip install --upgrade pip -r test-requirements.txt
      - run:
          name: Run unit tests
          command: export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/tests && pytest tests/* -p no:warnings

  deploy:
    working_directory: ~/repo
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install package
          command: pip install .
      - run:
          name: Get version
          command: |
            VERSION=$(python -c "import wqp; print(wqp.__version__)")
            echo Deploying version $VERSION...
            echo export WQP_VERSION=$VERSION >> $BASH_ENV
      - run:
          name: Build package
          command: |
            python setup.py sdist
            echo export TAR_FILE="dist/wqp-$WQP_VERSION.tar.gz" >> $BASH_ENV
      - run:
          name: Deploy package
          command: |
            echo Pushing file $TAR_FILE to gemfury...
            curl -F "package=@dist/wqp-$WQP_VERSION.tar.gz" "https://$FURY_PUSH_TOKEN@push.fury.io/$FURY_USER_NAME/"


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unittests:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only:
                - feature/ci
